find_path(Glog_INCLUDE_DIRS glog/logging.h /usr/include /usr/local/include)
find_library(Glog_LIBRARIES NAMES glog /usr/lib /usr/local/lib)
if(Glog_INCLUDE_DIRS AND Glog_LIBRARIES)
  set(Glog_FOUND TRUE)
  if(NOT Glog_FIND_QUIETLY)
    message(STATUS "Found Glog: ${Glog_LIBRARIES}")
  endif()
else()
  set(Glog_FOUND FALSE)
  if(Glog_FIND_REQUIRED)
    message(FATAL_ERROR "Could not find Glog")
  endif()
endif()
